[package]
name = "cargo-vendor-filterer"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
categories = ["development-tools::cargo-plugins", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
camino = "1.0"
clap = { version = "3.2", features = ["derive"] }
cargo_metadata = "0.11.3"