[package]
categories = ["development-tools::cargo-plugins", "command-line-utilities"]
edition = "2018"
license = "Apache-2.0"
name = "cargo-vendor-filterer"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
camino = "1.0"
cargo-lock = "8"
cargo_metadata = "0.11.3"

[dependencies.clap]
features = ["derive"]
version = "3.2"