[package]
categories = ["development-tools::cargo-plugins", "command-line-utilities"]
edition = "2021"
license = "Apache-2.0"
name = "cargo-vendor-filterer"
version = "0.1.0"

#### Example configuration to filter to platform
### [package.metadata.vendor-filter]
### platforms = ["x86_64-unknown-linux-gnu"]
### all-features = true

[dependencies]
anyhow = "1.0"
camino = "1.0"
cargo-lock = "8"
cargo_metadata = "0.11.3"
hex = "0.4"
toml = "0.5"
openssl = "0.10.40"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.80"

[dependencies.clap]
features = ["derive"]
version = "3.2"