# Inspired by https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/ci.yaml
# but tweaked in several ways.  If you make changes here, consider doing so across other
# repositories in e.g. ostreedev etc.
name: CI

permissions:
  actions: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, rust-src
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1
        with:
          key: "tests"
      - name: Build
        run: cargo test --no-run
      - name: Run tests
        run: cargo test -- --nocapture --quiet
      - name: Install
        run: cargo install --path . --debug
      - name: Self test integration
        run: ./ci/selftest.sh
